import '@fontsource/vazirmatn/400.css'; import '@fontsource/vazirmatn/500.css'; import '@fontsource/vazirmatn/700.css'; import { useEffect, useMemo, useState } from 'react'; import { createRoot } from 'react-dom/client'; import './style.css';
declare global { interface Window { repairShop: any } }
type Page = 'dashboard'|'work_orders'|'customers'|'vehicles'|'products'|'sales'|'purchases'|'cash_transactions'|'checks'|'suppliers'|'expenses';
const nav: [Page,string,string][] = [['dashboard','داشبورد','▦'],['work_orders','پذیرش تعمیرگاه','⌕'],['customers','مشتریان','♙'],['vehicles','خودروها','▱'],['products','انبار قطعات','▣'],['sales','فروش','▤'],['purchases','خرید','▧'],['cash_transactions','صندوق','◉'],['checks','چک‌ها','▱'],['suppliers','تأمین‌کنندگان','♧'],['expenses','هزینه‌ها','◒']];
const labels:any={customers:'مشتریان',vehicles:'خودروها',products:'انبار قطعات',sales:'فاکتورهای فروش',purchases:'فاکتورهای خرید',checks:'چک‌ها',suppliers:'تأمین‌کنندگان',expenses:'هزینه‌ها',cash_transactions:'گردش صندوق',work_orders:'پذیرش تعمیرگاه'};
const fmt=(n:any)=>new Intl.NumberFormat('fa-IR').format(Number(n||0));
const date=(v:string)=>new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium'}).format(new Date(v));
const fields:any={customers:[['name','نام و نام خانوادگی','text'],['phone','شماره تماس','tel'],['address','آدرس','text']],vehicles:[['plate','پلاک خودرو','text'],['brand','برند','text'],['model','مدل','text'],['color','رنگ','text'],['mileage','کیلومتر','number']],products:[['code','کد قطعه','text'],['name','نام قطعه','text'],['stock','موجودی اولیه','number'],['buy_price','قیمت خرید','number'],['sale_price','قیمت فروش','number'],['min_stock','حداقل موجودی','number']],suppliers:[['name','نام تأمین‌کننده','text'],['phone','شماره تماس','tel'],['address','آدرس','text']],checks:[['number','شماره چک','text'],['bank','نام بانک','text'],['amount','مبلغ','number'],['due_date','تاریخ سررسید','date']],expenses:[['title','عنوان هزینه','text'],['amount','مبلغ','number'],['category','دسته‌بندی','text']],cash_transactions:[['type','نوع تراکنش (receipt/payment)','text'],['amount','مبلغ','number'],['description','شرح','text']]};

function App(){ const [page,setPage]=useState<Page>('dashboard'),[data,setData]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[show,setShow]=useState(false),[query,setQuery]=useState('');
 const load=async()=>{setShow(false);setQuery(''); if(page==='dashboard')setData(await window.repairShop.dashboard());else setRows(await window.repairShop.list(page));}; useEffect(()=>{load()},[page]);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).includes(query)),[rows,query]);
 return <main><aside><div className="brand"><span>R</span><div>RepairShop <b>PRO</b><small>مدیریت هوشمند تعمیرگاه</small></div></div><nav>{nav.map(([id,name,icon])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><i>{icon}</i>{name}</button>)}</nav><div className="sideBottom"><button onClick={()=>window.repairShop.backup()}>⌄ پشتیبان‌گیری امن</button><small>نسخه ۱.۰.۰ • آفلاین</small></div></aside><section className="content"><header><div><p>امروز، {new Intl.DateTimeFormat('fa-IR',{weekday:'long',month:'long',day:'numeric'}).format(new Date())}</p><h1>{page==='dashboard'?'صبح بخیر، مدیر تعمیرگاه 👋':labels[page]}</h1></div><div className="topActions"><button className="iconBtn">⌕</button><button className="iconBtn">♟</button><div className="avatar">م</div></div></header>{page==='dashboard'?<Dashboard data={data}/>:<Listing page={page} rows={filtered} query={query} setQuery={setQuery} open={()=>setShow(true)} refresh={load}/>}</section>{show&&<Modal page={page} close={()=>setShow(false)} done={load}/>}</main> }
function Dashboard({data}:any){if(!data)return <div className="loading">در حال بارگذاری اطلاعات…</div>; const cards=[['فروش امروز',data.salesToday,'تومان','↗'],['موجودی صندوق',data.cashBalance,'تومان','◉'],['ارزش انبار',data.stockValue,'تومان','▣'],['خودروهای در تعمیر',data.activeOrders,'خودرو','⌕']];return <><div className="stats">{cards.map(([t,v,u,i])=><article className="stat" key={String(t)}><span className="statIcon">{i}</span><p>{t}</p><strong>{fmt(v)} <em>{u}</em></strong><small className="positive">▲ به‌روزرسانی لحظه‌ای</small></article>)}</div><div className="grid2"><article className="panel chart"><div className="panelHead"><div><h2>فروش ماهانه</h2><p>عملکرد ۶ ماه اخیر</p></div><b>۲۴,۸۰۰,۰۰۰ تومان</b></div><div className="bars">{[38,55,42,76,63,91].map((h,i)=><div key={i}><span style={{height:h+'%'}}></span><small>{['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور'][i]}</small></div>)}</div></article><article className="panel"><div className="panelHead"><div><h2>هشدار موجودی</h2><p>قطعات نیازمند تأمین</p></div><button className="textBtn">مشاهده انبار</button></div>{data.lowStock.map((p:any)=><div className="notice" key={p.id}><span>▣</span><div><b>{p.name}</b><small>کد: {p.code}</small></div><strong>{fmt(p.stock)} عدد</strong></div>)}</article></div><div className="grid2 lower"><article className="panel"><div className="panelHead"><div><h2>پذیرش‌های اخیر</h2><p>وضعیت خودروهای تعمیرگاه</p></div><button className="textBtn">مشاهده همه</button></div><table><thead><tr><th>کد پذیرش</th><th>مشتری</th><th>پلاک</th><th>وضعیت</th></tr></thead><tbody>{data.orders.map((o:any)=><tr key={o.id}><td>{o.code}</td><td>{o.customer}</td><td>{o.plate}</td><td><Status value={o.status}/></td></tr>)}</tbody></table></article><article className="panel activity"><div className="panelHead"><div><h2>آخرین فعالیت‌ها</h2><p>گردش امروز تعمیرگاه</p></div></div>{data.activity.map((a:any,i:number)=><div className="activityRow" key={i}><span>◉</span><div><b>{a.description}</b><small>{date(a.created_at)}</small></div><strong className={a.type==='receipt'?'green':''}>{a.type==='receipt'?'+':'-'}{fmt(a.amount)}</strong></div>)}</article></div></>}
function Status({value}:any){const x:any={pending:'در انتظار',in_progress:'در حال تعمیر',ready:'آماده تحویل',delivered:'تحویل شده'};return <span className={'status '+value}>{x[value]||value}</span>}
function Listing({page,rows,query,setQuery,open,refresh}:any){return <><div className="toolbar"><div className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجو در اطلاعات…"/></div>{fields[page]&&<button className="primary" onClick={open}>＋ ثبت {labels[page].replace('ها','')}</button>}</div><article className="panel tablePanel"><div className="panelHead"><div><h2>{labels[page]}</h2><p>{fmt(rows.length)} مورد ثبت‌شده</p></div></div><Table page={page} rows={rows} refresh={refresh}/></article></>}
function Table({page,rows,refresh}:any){const cols:any={customers:[['name','نام مشتری'],['phone','تماس'],['address','آدرس'],['balance','مانده حساب']],vehicles:[['plate','پلاک'],['brand','برند'],['model','مدل'],['customer_name','مالک'],['mileage','کیلومتر']],products:[['code','کد'],['name','نام قطعه'],['stock','موجودی'],['buy_price','خرید'],['sale_price','فروش']],work_orders:[['code','کد پذیرش'],['customer','مشتری'],['plate','خودرو'],['mechanic','تعمیرکار'],['status','وضعیت'],['labor_amount','اجرت']],checks:[['number','شماره چک'],['bank','بانک'],['amount','مبلغ'],['due_date','سررسید'],['status','وضعیت']],cash_transactions:[['type','نوع'],['amount','مبلغ'],['description','شرح'],['created_at','تاریخ']],expenses:[['title','عنوان'],['category','دسته‌بندی'],['amount','مبلغ'],['paid_at','تاریخ']]}; const c=cols[page]||Object.keys(rows[0]||{}).slice(0,5).map(k=>[k,k]); return <table className="dataTable"><thead><tr>{c.map(([k,n]:any)=><th key={k}>{n}</th>)}{page==='work_orders'&&<th>عملیات</th>}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}>{c.map(([k]:any)=><td key={k}>{k==='status'?<Status value={r[k]}/>:['amount','buy_price','sale_price','balance','labor_amount'].includes(k)?`${fmt(r[k])} تومان`:k.includes('created')||k==='paid_at'?date(r[k]):r[k]||'—'}</td>)}{page==='work_orders'&&<td><button className="tiny" onClick={async()=>{await window.repairShop.updateOrderStatus(r.id,r.status==='in_progress'?'ready':'delivered');refresh()}}>تغییر وضعیت</button></td>}</tr>)}{!rows.length&&<tr><td colSpan={c.length+1} className="empty">اطلاعاتی برای نمایش وجود ندارد.</td></tr>}</tbody></table>}
function Modal({page,close,done}:any){const [form,setForm]=useState<any>(page==='cash_transactions'?{type:'receipt'}:page==='checks'?{type:'received',status:'in_hand'}:{});const submit=async(e:any)=>{e.preventDefault();await window.repairShop.create(page,form);done()};return <div className="overlay"><form className="modal" onSubmit={submit}><div className="modalHead"><div><h2>ثبت {labels[page].replace('ها','')}</h2><p>اطلاعات را با دقت وارد کنید.</p></div><button type="button" onClick={close}>×</button></div><div className="formGrid">{(fields[page]||[]).map(([key,label,type]:any)=><label key={key}>{label}<input required={key==='name'||key==='title'||key==='amount'} type={type} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="modalFoot"><button type="button" className="ghost" onClick={close}>انصراف</button><button className="primary">ثبت اطلاعات</button></div></form></div>};createRoot(document.getElementById('root')!).render(<App/>);
