const {app,BrowserWindow,ipcMain,Menu}=require('electron'); const path=require('path'); const Database=require('better-sqlite3');
let db;
function initDb(){ const file=path.join(app.getPath('userData'),'repairshop-pro.sqlite'); db=new Database(file); db.pragma('foreign_keys = ON');
 db.exec(`CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY,name TEXT NOT NULL,phone TEXT,address TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vehicles(id INTEGER PRIMARY KEY,customer_id INTEGER NOT NULL REFERENCES customers(id),plate TEXT,brand TEXT,model TEXT,year TEXT);
CREATE TABLE IF NOT EXISTS mechanics(id INTEGER PRIMARY KEY,name TEXT NOT NULL,phone TEXT);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,sku TEXT UNIQUE,stock REAL DEFAULT 0,unit_price REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY,name TEXT NOT NULL,phone TEXT);
CREATE TABLE IF NOT EXISTS work_orders(id INTEGER PRIMARY KEY,code TEXT UNIQUE,customer_id INTEGER REFERENCES customers(id),vehicle_id INTEGER REFERENCES vehicles(id),mechanic_id INTEGER REFERENCES mechanics(id),status TEXT DEFAULT 'باز',description TEXT,total REAL DEFAULT 0,paid REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS work_order_items(id INTEGER PRIMARY KEY,work_order_id INTEGER REFERENCES work_orders(id),product_id INTEGER REFERENCES products(id),title TEXT,qty REAL DEFAULT 1,price REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY,supplier_id INTEGER REFERENCES suppliers(id),total REAL DEFAULT 0,paid REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS purchase_items(id INTEGER PRIMARY KEY,purchase_id INTEGER REFERENCES purchases(id),product_id INTEGER REFERENCES products(id),qty REAL,price REAL);
CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY,customer_id INTEGER REFERENCES customers(id),total REAL DEFAULT 0,paid REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sale_items(id INTEGER PRIMARY KEY,sale_id INTEGER REFERENCES sales(id),product_id INTEGER REFERENCES products(id),qty REAL,price REAL);
CREATE TABLE IF NOT EXISTS cash_transactions(id INTEGER PRIMARY KEY,kind TEXT,amount REAL,reference_type TEXT,reference_id INTEGER,description TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS checks(id INTEGER PRIMARY KEY,party_type TEXT,party_id INTEGER,amount REAL,due_date TEXT,status TEXT DEFAULT 'در جریان');
CREATE TABLE IF NOT EXISTS bank_accounts(id INTEGER PRIMARY KEY,name TEXT,account_no TEXT,balance REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS bank_transactions(id INTEGER PRIMARY KEY,account_id INTEGER REFERENCES bank_accounts(id),kind TEXT,amount REAL,description TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ledger_entries(id INTEGER PRIMARY KEY,party_type TEXT,party_id INTEGER,kind TEXT,amount REAL,reference_type TEXT,reference_id INTEGER,description TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY,title TEXT,amount REAL,paid_from TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS app_settings(key TEXT PRIMARY KEY,value TEXT);`);
 if(!db.prepare('SELECT count(*) c FROM customers').get().c){ const addC=db.prepare('INSERT INTO customers(name,phone,address) VALUES(?,?,?)'); addC.run('علی رضایی','09121234567','تهران، نارمک');addC.run('مریم احمدی','09123334455','تهران، پونک'); const c=db.prepare('SELECT id FROM customers').all(); db.prepare('INSERT INTO vehicles(customer_id,plate,brand,model,year) VALUES(?,?,?,?,?)').run(c[0].id,'12الف345-67','پژو','206 تیپ 5','1400'); db.prepare('INSERT INTO vehicles(customer_id,plate,brand,model,year) VALUES(?,?,?,?,?)').run(c[1].id,'88ب222-11','دنا','پلاس توربو','1401'); db.prepare("INSERT INTO mechanics(name,phone) VALUES('حسن کریمی','09120001122')").run(); const p=db.prepare('INSERT INTO products(name,sku,stock,unit_price) VALUES(?,?,?,?)');p.run('روغن موتور 10W-40','OIL-10',24,380000);p.run('فیلتر روغن پژو','FLT-206',18,95000);p.run('لنت جلو 206','BRK-206',10,850000); const wo=db.prepare("INSERT INTO work_orders(code,customer_id,vehicle_id,mechanic_id,status,description,total,paid) VALUES('WO-1001',1,1,1,'در حال انجام','تعویض روغن و سرویس دوره‌ای',475000,475000)").run(); db.prepare('INSERT INTO work_order_items(work_order_id,product_id,title,qty,price) VALUES(?,?,?,?,?)').run(wo.lastInsertRowid,1,'روغن موتور 10W-40',1,380000); db.prepare('INSERT INTO cash_transactions(kind,amount,reference_type,reference_id,description) VALUES(?,?,?,?,?)').run('دریافت',475000,'work_order',wo.lastInsertRowid,'پرداخت فاکتور WO-1001'); db.prepare('INSERT INTO ledger_entries(party_type,party_id,kind,amount,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?)').run('customer',1,'بدهکار',475000,'work_order',wo.lastInsertRowid,'خدمات تعمیر'); db.prepare('INSERT INTO ledger_entries(party_type,party_id,kind,amount,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?)').run('customer',1,'بستانکار',475000,'cash',wo.lastInsertRowid,'پرداخت نقدی'); }
 return file; }
function query(type){const maps={customers:`SELECT c.*,COALESCE(SUM(CASE WHEN l.kind='بدهکار' THEN l.amount ELSE -l.amount END),0) balance FROM customers c LEFT JOIN ledger_entries l ON l.party_type='customer' AND l.party_id=c.id GROUP BY c.id ORDER BY c.id DESC`,vehicles:'SELECT v.*,c.name customer_name FROM vehicles v JOIN customers c ON c.id=v.customer_id ORDER BY v.id DESC',products:'SELECT * FROM products ORDER BY id DESC',work_orders:'SELECT w.*,c.name customer_name,v.plate FROM work_orders w LEFT JOIN customers c ON c.id=w.customer_id LEFT JOIN vehicles v ON v.id=w.vehicle_id ORDER BY w.id DESC'}; return db.prepare(maps[type]).all()}
app.whenReady().then(()=>{initDb();Menu.setApplicationMenu(null);const win=new BrowserWindow({width:1300,height:820,minWidth:1000,minHeight:650,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}}); win.loadURL(process.env.VITE_DEV_SERVER_URL||`file://${path.join(__dirname,'../dist/index.html')}`);});
ipcMain.handle('login',(_,pin)=>pin==='1234'); ipcMain.handle('list',(_,t)=>query(t)); ipcMain.handle('database:path',()=>path.join(app.getPath('userData'),'repairshop-pro.sqlite'));ipcMain.handle('dashboard',()=>({customers:db.prepare('SELECT count(*) c FROM customers').get().c,orders:db.prepare("SELECT count(*) c FROM work_orders WHERE status != 'تکمیل شده'").get().c,stock:db.prepare('SELECT COALESCE(SUM(stock*unit_price),0) c FROM products').get().c,cash:db.prepare("SELECT COALESCE(SUM(CASE WHEN kind='دریافت' THEN amount ELSE -amount END),0) c FROM cash_transactions").get().c}));
ipcMain.handle('create',(_,type,x)=>{if(type==='customers') db.prepare('INSERT INTO customers(name,phone,address) VALUES(?,?,?)').run(x.name,x.phone||'',x.address||''); if(type==='vehicles') db.prepare('INSERT INTO vehicles(customer_id,plate,brand,model,year) VALUES(?,?,?,?,?)').run(x.customer_id,x.plate,x.brand,x.model,x.year); return query(type)});
ipcMain.handle('work-order:create',(_,x)=>{const tx=db.transaction(()=>{const r=db.prepare("INSERT INTO work_orders(code,customer_id,vehicle_id,status,description,total,paid) VALUES(?,?,?,?,?,?,?)").run(`WO-${Date.now().toString().slice(-6)}`,x.customer_id,x.vehicle_id,'باز',x.description,x.total,x.paid); if(x.product_id&&x.qty){db.prepare('INSERT INTO work_order_items(work_order_id,product_id,title,qty,price) SELECT ?,id,name,?,unit_price FROM products WHERE id=?').run(r.lastInsertRowid,x.qty,x.product_id);db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(x.qty,x.product_id)} db.prepare('INSERT INTO ledger_entries(party_type,party_id,kind,amount,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?)').run('customer',x.customer_id,'بدهکار',x.total,'work_order',r.lastInsertRowid,'خدمات تعمیر');if(x.paid){db.prepare('INSERT INTO cash_transactions(kind,amount,reference_type,reference_id,description) VALUES(?,?,?,?,?)').run('دریافت',x.paid,'work_order',r.lastInsertRowid,'پرداخت نقدی');db.prepare('INSERT INTO ledger_entries(party_type,party_id,kind,amount,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?)').run('customer',x.customer_id,'بستانکار',x.paid,'cash',r.lastInsertRowid,'پرداخت نقدی')}});tx();return query('work_orders')});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
